### ISSUE TITLE
working with git missing add

### ISSUE THREAD

**Issue by shashinka** [CiscoDevNet/devnet-express-security-issues#4]
https://learninglabs.cisco.com/tracks/devnet-express-security/intro-python/git-basic-workflows/step/3

there is no step to do a git add of the change_me file

**Comment by annegentle** [comment]
Hi, just wanted to say thanks for reporting a bit of confusion! 

Since the file already exists in the Git repo that you cloned, you do not need to do a `git add` command. Git's already tracking `change_me.txt`. If you add a new file, such as `random-file.txt`, then you would need to do a `git add random-file.txt`. Hope that you got it all cleared up!
